server:
    port: 9001
spring:
    application:
        name: binary-eureka-server
eureka:
    instance:
        hostname: peer1
    client:
        service-url:
            defaultZone: http://peer2:9002/eureka/