server:
    port: 9002
spring:
    application:
        name: binary-eureka-server
eureka:
    instance:
        hostname: peer2
    client:
        service-url:
            defaultZone: http://peer1:9001/eureka/