server:
    port: 9000

spring:
    application:
        name: feign-eureka-server

eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://localhost:${server.port}/eureka/
